version: '3.7'

services:
  swedish-driving-license-test-finder:
    hostname: swedish-driving-license-test-finder
    ports:
      - "9528:9528"
      - "9529:9529"
    image: bmd007/license-test-finder
    environment:
      ssn: "-"
      telegram_bot_token: "bot5291539544:AAHTAjCZaLYZG4Oc3jMr_Ct5xQnKY77W5xE"
      chat_id: "407218480"
      time_window_start: "2024-11-01"  #YYYY-MM-DD
      time_window_end: "2025-02-20"  #YYYY-MM-DD
