version: '3.7'

services:
  swedish-driving-license-test-finder:
    hostname: swedish-driving-license-test-finder
    ports:
      - "9528:9528"
      - "9529:9529"
    image: bmd007/license-test-finder:latest
    environment:
      ssn: "-"
      telegram_bot_token: "bot5291539544:AAHTAjCZaLYZG4Oc3jMr_Ct5xQnKY77W5xE"
      chat_id: "41846159"
      time_window_start: "2022-04-01"  #YYYY-MM-DD
      time_window_end: "2022-06-30"  #YYYY-MM-DD

